# Generated by Django 5.2.8 on 2025-12-05 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroompublic',
            name='guest',
        ),
        migrations.DeleteModel(
            name='Guest',
        ),
    ]
